### ISSUE TITLE
Video class missing Official and PublishedAt

### ISSUE THREAD

**Issue by Miatrix** [jellyfin/TMDbLib#413]
From their API Documents: https://developers.themoviedb.org/3/movies/get-movie-videos

`{
  "id": 550,
  "results": [
    {
      "iso_639_1": "en",
      "iso_3166_1": "US",
      "name": "Fight Club - Theatrical Trailer Remastered in HD",
      "key": "6JnN1DmbqoU",
      "site": "YouTube",
      "size": 1080,
      "type": "Trailer",
      "official": false,
      "published_at": "2015-02-26T03:19:25.000Z",
      "id": "5e382d1b4ca676001453826d"
    },
    {
      "iso_639_1": "en",
      "iso_3166_1": "US",
      "name": "Fight Club | #TBT Trailer | 20th Century FOX",
      "key": "BdJKm16Co6M",
      "site": "YouTube",
      "size": 1080,
      "type": "Trailer",
      "official": true,
      "published_at": "2014-10-02T19:20:22.000Z",
      "id": "5c9294240e0a267cd516835f"
    }
  ]
}`

**Comment by bigjam** [comment]
I need these fields too, i can see they also  added a new "include_video_language" filter like "include_image_language" it will be cool to add these new field too.
Thx for helpers.

From TMDB website :
"July 28, 2021 | A new include_video_language filter is now available. You can use this filter the same way you use include_image_language on image calls. We also added two new fields, official and published_at to the video response."

**Comment by Miatrix** [comment]
Implemented in https://github.com/jellyfin/TMDbLib/pull/472
